### ISSUE TITLE
error: NotAuthenticated: Invalid login

### ISSUE THREAD

**Issue by Revozop** [p3nt4/Nuages#27]
Tested on Windows 10 Machine, after i try login using !login myusername, after put password, this error appear

error: NotAuthenticated: Invalid login
    at new NotAuthenticated (C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\errors\lib\index.js:93:17)
    at LocalStrategy.<anonymous> (C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:44:23)
    at Generator.next (<anonymous>)
    at C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:4:12)
    at LocalStrategy.findEntity (C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:41:16)
    at LocalStrategy.<anonymous> (C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:102:39)
    at Generator.next (<anonymous>)
    at C:\Users\Admin\Desktop\Nuages-master\Server\node_modules\@feathersjs\authentication-local\lib\strategy.js:8:71

**Comment by p3nt4** [comment]
Looks like you did not put the right user/password.

You can manage users with the setup.js script in the Server directory.

**Comment by Revozop** [comment]
i have put correctly password and user, this errors appear on windows 10 machine with nodejs 16

**Comment by p3nt4** [comment]
I tested on Windows 10 and confirmed the issue. I will debug and get back to you.

**Comment by p3nt4** [comment]
I have fixed the bug.

To fix your install you want to update this line in Server\config\production.js:
`"usernameField": "username",`

to 

`"usernameField": "\\username",`

**Comment by Revozop** [comment]
thanks master!
